// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeviceInteractionServiceClient is the client API for DeviceInteractionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceInteractionServiceClient interface {
	CreateDeviceInteraction(ctx context.Context, in *CreateDeviceInteractionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type deviceInteractionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceInteractionServiceClient(cc grpc.ClientConnInterface) DeviceInteractionServiceClient {
	return &deviceInteractionServiceClient{cc}
}

func (c *deviceInteractionServiceClient) CreateDeviceInteraction(ctx context.Context, in *CreateDeviceInteractionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/main.DeviceInteractionService/CreateDeviceInteraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceInteractionServiceServer is the server API for DeviceInteractionService service.
// All implementations must embed UnimplementedDeviceInteractionServiceServer
// for forward compatibility
type DeviceInteractionServiceServer interface {
	CreateDeviceInteraction(context.Context, *CreateDeviceInteractionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDeviceInteractionServiceServer()
}

// UnimplementedDeviceInteractionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceInteractionServiceServer struct {
}

func (UnimplementedDeviceInteractionServiceServer) CreateDeviceInteraction(context.Context, *CreateDeviceInteractionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceInteraction not implemented")
}
func (UnimplementedDeviceInteractionServiceServer) mustEmbedUnimplementedDeviceInteractionServiceServer() {
}

// UnsafeDeviceInteractionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceInteractionServiceServer will
// result in compilation errors.
type UnsafeDeviceInteractionServiceServer interface {
	mustEmbedUnimplementedDeviceInteractionServiceServer()
}

func RegisterDeviceInteractionServiceServer(s grpc.ServiceRegistrar, srv DeviceInteractionServiceServer) {
	s.RegisterService(&DeviceInteractionService_ServiceDesc, srv)
}

func _DeviceInteractionService_CreateDeviceInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceInteractionServiceServer).CreateDeviceInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.DeviceInteractionService/CreateDeviceInteraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceInteractionServiceServer).CreateDeviceInteraction(ctx, req.(*CreateDeviceInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceInteractionService_ServiceDesc is the grpc.ServiceDesc for DeviceInteractionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceInteractionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.DeviceInteractionService",
	HandlerType: (*DeviceInteractionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeviceInteraction",
			Handler:    _DeviceInteractionService_CreateDeviceInteraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
