name: Pipeline for DEV environment
on:
  push:
    paths: [client/**, ./github/**]
    branches: [develop, master]
env:
  APP_ENV: dev
  APP_NAME: go-grpc-headless-service-client

jobs:
  create_app_artifacts:
    name: The entry point to trigger related jobs to satisfy this pipeline
    runs-on: ubuntu-latest
    environment: $APP_ENV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Build and publish image
        id: build-publish-image
        uses:  ./.github/actions/build_deploy_image
        with:
          environment: ${{ env.APP_ENV }}
          docker-file: ${{ github.workspace }}/client/Dockerfile
          base-repository-url: https://${{ vars.ARTIFACT_REGION }}-docker.pkg.dev
          image-url: https://${{ vars.ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.ARTIFACT_PROJECT_ID }}/${{ env.APP_NAME }}/${{ env.APP_ENV }}
          gcr-credential: ${{ secrets.GCR_CREDENTIAL }}
